# Generated by Django 3.0.7 on 2020-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('movierating', models.CharField(max_length=10)),
                ('movieyear', models.CharField(max_length=5)),
                ('movieimage', models.CharField(max_length=5000)),
            ],
        ),
    ]
